In [2]:
import pandas as pd

In [3]:
df_raw = pd.read_csv('beer_reviews.csv')
df_raw.columns

Index(['brewery_id', 'brewery_name', 'review_time', 'review_overall',
       'review_aroma', 'review_appearance', 'review_profilename', 'beer_style',
       'review_palate', 'review_taste', 'beer_name', 'beer_abv',
       'beer_beerid'],
      dtype='object')

In [4]:
df = df_raw[[ 'review_overall',
       'review_aroma', 'review_appearance', 'review_profilename', 'beer_style',
       'review_palate', 'review_taste', 'beer_name',
       'beer_beerid']]

In [5]:
df_na = df
beer_count = df_na.groupby(['beer_name', 'beer_beerid']).count()['review_overall']
beer_avg = df_na.groupby(['beer_name', 'beer_beerid']).mean()
beer_avg['review_count'] = beer_count

In [6]:
beer_df = beer_avg.reset_index()
beer_clean = beer_df.set_index('beer_name')

In [7]:
sorted_df = beer_clean.sort_values(by = 'review_count', ascending= False)
beer_feature_count = sorted_df.groupby(['beer_name', 'beer_beerid']).count()['review_aroma']

In [8]:
df_na.groupby(['beer_name', 'beer_beerid']).count()['review_aroma'].sort_values(ascending = False)

beer_name                            beer_beerid
90 Minute IPA                        2093           3290
Old Rasputin Russian Imperial Stout  412            3111
Sierra Nevada Celebration Ale        1904           3000
Two Hearted Ale                      1093           2728
Stone Ruination IPA                  4083           2704
                                                    ...
Kamakura Prime Beer Hoshi No Taiga   75889             1
Kama Sumatra                         29606             1
Kaltentaler Tuba-Weisse              40393             1
Kaltentaler Horn-Zwickl              40392             1
葉山ビール (Hayama Beer)                  70327             1
Name: review_aroma, Length: 66055, dtype: int64

In [9]:
beer_table = df_raw.groupby(['beer_name', 'beer_beerid']).mean()[['brewery_id','review_overall',	'review_aroma',	'review_appearance',	'review_palate',	'review_taste']]
beer_count = df_raw.groupby(['beer_name', 'beer_beerid']).count()['review_overall']
beer_table['review_count'] = beer_count

In [39]:
beer_1000 = beer_table.sort_values(by = 'review_count', ascending = False).head(10000)
beer_reset = beer_1000.reset_index()
beer_df = beer_reset
beer_df['Beer_name'] = beer_reset['beer_name']
beer_table = beer_df.set_index('Beer_name')

In [80]:
brewery_table = df_raw.groupby(['brewery_id']).mean()[['review_overall',	'review_aroma',	'review_appearance',	'review_palate',	'review_taste']]
brewery_count = df_raw.groupby(['brewery_id']).count()['review_overall']
brewery_table['review_count'] = brewery_count
brewery_df = brewery_table.sort_values(by = 'review_count', ascending = False)
brewery_df

,review_overall,review_aroma,review_appearance,review_palate,review_taste,review_count
brewery_id,,,,,,
35,3.689522,3.593107,3.809299,3.641365,3.647171,39444
10099,3.836047,3.916945,3.943763,3.895860,3.971350,33839
147,4.040268,4.094644,4.152422,4.073550,4.150608,33066
140,4.056207,3.896682,4.096971,3.965184,4.028764,28751
287,3.973066,3.938331,3.983724,3.965484,4.011572,25191
...,...,...,...,...,...,...
24502,4.000000,3.000000,2.500000,3.500000,3.500000,1
17224,3.500000,4.000000,3.500000,3.000000,3.500000,1
24526,2.500000,2.500000,3.000000,3.000000,2.500000,1
17216,4.000000,3.500000,3.000000,4.000000,4.000000,1
15048,3.500000,4.000000,4.000000,2.000000,4.000000,1

In [64]:
aroma_table = beer_df.sort_values(by=['review_aroma', 'review_count'], ascending = [False,False]).head(10000).set_index('beer_name')
appearance_table = beer_df.sort_values(by=['review_appearance', 'review_count'], ascending = [False,False]).head(10000).set_index('beer_name')
palate_table = beer_df.sort_values(by=['review_palate', 'review_count'], ascending = [False,False]).head(10000).set_index('beer_name')
taste_table = beer_df.sort_values(by=['review_taste', 'review_count'], ascending = [False,False]).head(10000).set_index('beer_name')
taste_table

,beer_beerid,brewery_id,review_overall,review_aroma,review_appearance,review_palate,review_taste,review_count,Beer_name
beer_name,,,,,,,,,
M Belgian-Style Barleywine,24273,385.0,4.750000,4.785714,4.482143,4.803571,4.857143,28,M Belgian-Style Barleywine
Rare D.O.S.,63649,22147.0,4.848485,4.757576,4.469697,4.803030,4.848485,33,Rare D.O.S.
De Dolle Stille Nacht Special Reserva 2000,7289,201.0,4.578947,4.526316,4.263158,4.526316,4.789474,19,De Dolle Stille Nacht Special Reserva 2000
Rare Bourbon County Stout,62397,1549.0,4.544177,4.658635,4.269076,4.594378,4.767068,249,Rare Bourbon County Stout
Dirty Horse,44910,15237.0,4.820513,4.615385,4.423077,4.576923,4.743590,39,Dirty Horse
...,...,...,...,...,...,...,...,...,...
Earthquake High Gravity Lager,51067,782.0,1.612245,1.744898,2.163265,1.693878,1.438776,49,Earthquake High Gravity Lager
Genuine ALE,4683,881.0,1.472222,1.583333,2.138889,1.722222,1.388889,18,Genuine ALE
Stite Golden Pilsner,2935,892.0,1.333333,1.416667,2.222222,1.500000,1.361111,18,Stite Golden Pilsner
Evil Eye,20705,1422.0,1.471154,1.509615,2.221154,1.682692,1.355769,52,Evil Eye
Carlton Cold,2856,353.0,1.583333,1.479167,1.979167,1.583333,1.354167,24,Carlton Cold

In [56]:
from pymongo import MongoClient
from config import mongo_uri

collection = MongoClient(mongo_uri).beer_db.beer_table
collection.insert_one(beer_table.to_dict())

In [58]:
collection = MongoClient(mongo_uri).beer_db.feature_tables
collection.insert_many([aroma_table.to_dict(), appearance_table.to_dict(), palate_table.to_dict(), taste_table.to_dict()])